services:
    - name: mysql:5.7
      alias: mysqlhost

variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: homestead
    MYSQL_PORT: 3377
    DB_HOST: mysqlhost

cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - vendor

stages:
    - test

test:phpunit:
    stage: test
    image: epcallan/php7-testing-phpunit:7.2-phpunit7
    tags:
        - linux
    before_script:
        - sleep 60s # wait for MySQL (TODO find a better solution...)
        - composer install --prefer-dist --no-ansi --no-interaction
    script:
        - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --stderr
