cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - vendor

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql

stages:
    - test

test:phpunit:
    stage: test
    image: epcallan/php7-testing-phpunit:7.2-phpunit7
    services:
        - mysql:5.7
    tags:
        - linux
    before_script:
        - composer install --prefer-dist --no-ansi --no-interaction
    script:
        - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
